DFI/Models/Facility.cs
using System;
using System.Collections.Generic;

namespace DFI.Models
{
    public class Facility
    {
        public Facility()
        {
            Documents = new HashSet<Document>();
            FacilityLocations = new HashSet<FacilityLocation>();
        }
        public int FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string Email { get; set; }
        public string PayType { get; set; }
        public string BillingEmail { get; set; }
        public int Status { get; set; }
        public DateTime AddDate { get; set; }
        public DateTime? DateOfModified { get; set; }
        public DateTime? StatusChangedDate { get; set; }
        public int? StatusChangedBy { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<FacilityLocation> FacilityLocations { get; set; }   
    }
}

DFI/Models/FacilityLocation.cs
using System;
using System.Collections.Generic;
using DFI.Helpers;

namespace DFI.Models
{
    public class FacilityLocation
    {
        public FacilityLocation()
        {
            Requests = new HashSet<Request>();
            FacilityHours = new HashSet<FacilityHour>();
            TempFacilityDistances = new HashSet<TempFacilityDistance>();
        }

        public int FacilityLocationId { get; set; }
        public string AddressLine1 { get; set; }
        public string Apartment { get; set; }
        public string City { get; set; }
        public string StateName { get; set; }
        public string Zipcode { get; set; }
        public string FullAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string DoctorsName { get; set; }
        public string WebsiteAddress { get; set; }
        public string ChartingSoftware { get; set; }
        public string XRaySoftware { get; set; }
        public string AllowedAdultProphylaxisTime { get; set; }
        public string AllowedChildProphylaxisTime { get; set; }
        public string PaidEndOfTheDay { get; set; }
        public string AdditionalInfo { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string TimeZoneId { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int LocationStatus { get; set; }

        public virtual Facility Facility { get; set; }
        public int FacilityId { get; set; }

        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<FacilityHour> FacilityHours { get; set; }
        public virtual ICollection<TempFacilityDistance> TempFacilityDistances { get; set; }
        
        public int? OffsetHours {
            get
            {
                var utcOffset = new DateTimeOffset(DateTime.UtcNow, TimeSpan.Zero);
                return TimeZoneInfo.GetUtcOffset(utcOffset).Hours;
            }
        }

        private TimeZoneInfo TimeZoneInfo => 
            string.IsNullOrEmpty(TimeZoneId)
                ? CommonConstants.DefaultTimeZone
                : TimeZoneInfo.FindSystemTimeZoneById(TimeZoneId);
    }
}

DFI/Controllers/FacilitiesController.cs
using System.Linq;
using System.Web.Mvc;
using DFI.Data.Accounts;
using DFI.Data.ChartingSoftwares;
using DFI.Data.Emails;
using DFI.Data.Facilities;
using DFI.Data.XraySoftwares;
using DFI.Helpers;
using Hangfire;

namespace DFI.Controllers
{
    public class FacilitiesController : Controller
    {
        private readonly IFacilityService _facilityService;
        
        private readonly IXraySoftwareService _xraySoftwareService;
        
        private readonly IChartingSoftwareService _chartingSoftwareService;

        public FacilitiesController(
            IFacilityService facilityService,
            IXraySoftwareService xraySoftwareService,
            IChartingSoftwareService chartingSoftwareService)
        {
            _facilityService = facilityService;
            _xraySoftwareService = xraySoftwareService;
            _chartingSoftwareService = chartingSoftwareService;
        }

        [Authorize(Roles = Role.Admin)]
        [HttpGet]
        public ActionResult Index()
        {
            var email = HttpContext.User.Identity.Name;
            var result = new FacilitySearchDto();
            return View(result);
        }

        [Authorize(Roles = Role.Admin)]
        [HttpPost]
        public PartialViewResult Search(FacilitySearchDto dto)
        {
            var searchDto = dto ?? new FacilitySearchDto();
            var result = _facilityService.GetListFacilityDtos(searchDto);
            return PartialView("_FacilitiesList", result);
        }

        [Authorize(Roles = Role.Admin)]
        [HttpGet]
        public ActionResult Facility(int? id)
        {
            var facility = _facilityService.GetFacility(id);
            return View(facility);
        }

        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        [HttpPost]
        public ActionResult Facility(FacilityDto dto)
        {
            if (ModelState.IsValid)
            {
                _facilityService.UpdateFacility(dto);
                return new EmptyResult();
            }

            var errors = ModelState.Values.SelectMany(c => c.Errors).Select(x => x.ErrorMessage).ToList();
            return Json(string.Join("<br/>", errors));
        }

        [Authorize(Roles = Role.Admin)]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var validationStatus = _facilityService.SetStatus(id, Helper.EState.Deleted);

            if (validationStatus.Success)
                validationStatus.Messages.Add(Helper.EState.Deleted.ToString().ToLowerInvariant());

            return Json(validationStatus);
        }

        [Authorize(Roles = Role.Admin)]
        [HttpPost]
        public ActionResult Activate(int id)
        {
            var validationStatus = _facilityService.SetStatus(id, Helper.EState.Active);

            if (validationStatus.Success)
                validationStatus.Messages.Add(Helper.EState.Active.ToString().ToLowerInvariant());

            return Json(validationStatus);
        }

        [Authorize(Roles = Role.Admin)]
        [HttpPost]
        public ActionResult Deactivate(int id)
        {
            var validationStatus = _facilityService.SetStatus(id, Helper.EState.InActive);

            if (validationStatus.Success)
                validationStatus.Messages.Add(Helper.EState.InActive.ToString().ToLowerInvariant());

            return Json(validationStatus);
        }

        [Authorize(Roles = Role.Facility)]
        [HttpGet]
        public ActionResult MyProfile()
        {
            var email = HttpContext.User.Identity.Name;
            return View("Facility", _facilityService.GetProfile(email));
        }

        [Authorize(Roles = Role.Admin + "," + Role.Temp)]
        [HttpGet]
        public ActionResult GetFacilityNames(EFacilityNameFor eFacilityNameFor)
        {
            return Json(_facilityService.GetFacilityNames(eFacilityNameFor), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = Role.Admin + "," + Role.Temp)]
        [HttpGet]
        public ActionResult GetFacilityEmails()
        {
            return Json(_facilityService.GetFacilityEmails(), JsonRequestBehavior.AllowGet);
        }
        
        [Authorize(Roles = Role.Admin + "," + Role.Temp)]
        [HttpGet]
        public ActionResult GetFacilityPhoneNumbers()
        {
            return Json(_facilityService.GetFacilityPhoneNumbers(), JsonRequestBehavior.AllowGet);
        }
        
        [Authorize(Roles = Role.Admin + "," + Role.Temp)]
        [HttpGet]
        public ActionResult GetFacilityCities()
        {
            return Json(_facilityService.GetFacilityCities(), JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public ActionResult GetXraySoftwareNames()
        {
            return Json(_xraySoftwareService.GetXraySoftwareNames(), JsonRequestBehavior.AllowGet);
        }
        
        [HttpGet]
        public ActionResult GetChartingSoftwareNames()
        {
            return Json(_chartingSoftwareService.GetChartingSoftwareNames(), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        [HttpGet]
        public ActionResult GetFacilityLocation(int? facilityId, int? facilityLocationId)
        {

            var dto = _facilityService.GetFacilityLocationDto(facilityId, facilityLocationId, User.IsInRole(Role.Admin), HttpContext.User.Identity.Name);
            return View("FacilityLocation", dto);
        }

        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        [HttpPost]
        public ActionResult CreateUpdateFacilityLocation(FacilityLocationDto dto)
        {
            if (ModelState.IsValid)
            {
                if(dto.Id.HasValue && dto.Id > 0)
                {
                    dto.WhoModified = HttpContext.User.Identity.Name;
                }
                else
                {
                    dto.WhoCreated = HttpContext.User.Identity.Name;
                }

                var result = _facilityService.SubmitFacilityLocationForm(dto);
                if (result.Success)
                {
                    if (result.Messages.Any())
                        return Json(int.Parse(result.Messages.FirstOrDefault())); //send location id for redirect to proper url

                    return new EmptyResult();
                }
                    
                return Json(string.Join("<br/>", result.Messages));
            }

            var errors = ModelState.Values.SelectMany(c => c.Errors).Select(x => x.ErrorMessage).ToList();
            return Json(string.Join("<br/>", errors));
        }

        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        [HttpGet]
        public ActionResult GetLocationsForFacility(int? facilityId)
        {
            return Json(_facilityService.GetFacilityLocations(facilityId ?? 0), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        [HttpPost]
        public ActionResult DeleteFacilityLocation(int locationId)
        {
            var validationStatus = _facilityService.DeleteLocation(locationId, User.IsInRole(Role.Admin), HttpContext.User.Identity.Name);
            return Json(validationStatus);
        }

        [Authorize(Roles = Role.Admin)]
        [HttpPost]
        public ActionResult SendBulkEmails(FacilityEmailLightDto dto)
        {
            BackgroundJob.Enqueue<IFacilityService>(c => c.SendBulkEmails(dto));
            return new EmptyResult();
        }

        [Authorize(Roles = Role.Admin)]
        [HttpPost]
        public ActionResult SendDirectlyEmail(EmailDto dto)
        {
            BackgroundJob.Enqueue<IEmailService>(c => c.AddEmail(dto));
            return new EmptyResult();
        }
    }
}

DFI/Views/Facilities/FacilityLocation.cshtml
@using DFI.Helpers
@using DFI.Data.Facilities
@using DFI.Data.Accounts
@using System.Web.Mvc.Html
@model DFI.Data.Facilities.FacilityLocationDto
@{
    ViewBag.Title = "FacilityLocation";
}

<h2>Location</h2>
@Html.Hidden("IsFacilityLogIn", this.User.IsInRole(Role.Facility))

@using (Ajax.BeginForm("CreateUpdateFacilityLocation", "Facilities", null, new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    LoadingElementId = "spinner",
    OnSuccess = "fnSuccess"
}, new { enctype = "multipart/form-data", id = "FacilityLocationForm" }))
{
    <script type="text/javascript">
        function fnSuccess(data) {
            isBusy = false;
            if (data && typeof data !== 'number') {
                $("#validationMessageId").html(data);
                $("#validationMessageId").show();
            } else {
                $("#validationMessageId").hide();
                $("#createFacilityLocation").attr("disabled", "disabled");
                $("#successMessage").show();

                setTimeout(function () {
                    $("#successMessage").hide();

                    if (location.search.indexOf("facilityLocationId") > 0) //this param has when update location
                    {
                        $("#createFacilityLocation").removeAttr('disabled');
                    }
                    else {

                        var isAdmin = "@User.IsInRole(Role.Admin)";
                        if (isAdmin == "True") {
                            var facilityId = $("#FacilityId").val();
                            window.location.href = window.location.origin + "/Facilities/Facility/" + facilityId;
                        } else {
                            window.location.href = window.location.origin + "/Facilities/MyProfile";
                        }

                    }

                }, 5000)
            }
        }
    </script>

    @Html.HiddenFor(c => c.Id)
    @Html.HiddenFor(c => c.FacilityId)
    @Html.HiddenFor(c => c.AddressFromGoogle, new { data_id = "addressFromGoogle" })



    <div class="form-group row">
        @Html.LabelFor(model => model.Apartment, "Suite number", new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.Apartment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment)
        </div>
    </div>

    @Html.Partial("_Map")

    <div>
        <h4>Office hours</h4>
        @for (int i = 0; i < Model.FacilityHours.Count; i++)
        {
            @Html.HiddenFor(c => c.FacilityHours[i].DayOfWeek);
            <div class="form-group row">
                @Html.LabelFor(model => model.FacilityHours[i].RangeHours, Model.FacilityHours[i].DayOfWeek, new { @class = "col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.FacilityHours[i].RangeHours, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FacilityHours[i].RangeHours)
                </div>
            </div>

        }
    </div>
    <hr />
    <div class="form-group row">
        @Html.LabelFor(model => model.PhoneNumber, "Phone number", new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.DoctorsName, "Doctors name", new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.DoctorsName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DoctorsName)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.WebsiteAddress, "Website address", new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.WebsiteAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WebsiteAddress)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(c => c.ChartingSoftware, "Charting software", new { @class = "col-sm-3" })
        <div class="col-sm-3">
            @Html.EditorFor(c => c.ChartingSoftware, new { htmlAttributes = new { @class = "form-control", @data_type = "autocomplete-input", @data_action = "/Facilities/GetChartingSoftwareNames" } })
            @Html.ValidationMessageFor(model => model.ChartingSoftware)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(c => c.XRaySoftware, "X-ray software", new { @class = "col-sm-3" })
        <div class="col-sm-3">
            @Html.EditorFor(c => c.XRaySoftware, new { htmlAttributes = new { @class = "form-control", @data_type = "autocomplete-input", @data_action = "/Facilities/GetXraySoftwareNames" } })
            @Html.ValidationMessageFor(model => model.XRaySoftware)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.AllowedAdultProphylaxisTime, "Allowed adult prophylaxis time (minutes)", new { @class = "col-sm-3" })
        <div class="col-sm-3">
            @Html.DropDownListFor(c => c.AllowedAdultProphylaxisTime, new SelectList(new List<string> { "30-40", "40-50", "50-60" }), "Select time", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AllowedAdultProphylaxisTime)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.AllowedChildProphylaxisTime, "Allowed child prophylaxis time (minutes)", new { @class = "col-sm-3" })
        <div class="col-sm-3">
            @Html.DropDownListFor(c => c.AllowedChildProphylaxisTime, new SelectList(new List<string> { "30-40", "40-50", "50-60" }), "Select time", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.AllowedChildProphylaxisTime)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(c => c.PaidEndOfTheDay, "Paid end of the day", new { @class = "col-sm-3" })
        <div class="col-sm-3">
            @Html.DropDownListFor(c => c.PaidEndOfTheDay, new SelectList(Enum.GetValues(typeof(EPay)).Cast<EPay>().Select(x => x.GetDisplayName())), "Select payment method", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PaidEndOfTheDay)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.AdditionalInfo, "Is there any additional information about your office that you feel is valuable for us to know?", new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.TextAreaFor(model => model.AdditionalInfo, new { @class = "form-control", rows = 5 })
            @Html.ValidationMessageFor(model => model.AdditionalInfo)
        </div>
    </div>

    <div class="alert alert-danger" style="display: none" data-id="validationMessage" id="validationMessageId" role="alert"></div>
    <div class="alert alert-success" style="display: none" id="successMessage" role="alert">Location has been created or updated.</div>

    <div class="alert alert-danger" style="display: none" id="deleteLocationValidationMessage" role="alert"></div>
    <div class="alert alert-success" style="display: none" id="deleteLocationSuccessMessage" role="alert">Deleted successfully</div>

    if (this.User.IsInRole(Role.Admin))
    {
        @Html.ActionLink("Back", "Facility", "Facilities", new { id = Model.FacilityId }, new { @class = "btn btn-secondary", @id = "backButton" })
    }
    else
    {
        @Html.ActionLink("Back", "MyProfile", "Facilities", null, new { @class = "btn btn-secondary", @id = "backButton" })
    }

    <button type="submit" class="btn btn-success" id="createFacilityLocation">Submit</button>

    if (Model.Id > 0 && !Model.IsOnlyOne)
    {
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteLocationModal">Delete</button>
    }
}

@if (Model.Id > 0 && !Model.IsOnlyOne)
{
    <div class="modal fade" id="deleteLocationModal" tabindex="-1" role="dialog" aria-labelledby="deleteLocationModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteLocationLabel">Delete location</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="deleteLocationBody">
                        Are you sure? This location will not be available for a new requests.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="button" id="deleteLocation" data-id="@Model.Id" class="btn btn-primary" data-dismiss="modal">Yes</button>
                </div>
            </div>
        </div>
    </div>
}

@Styles.Render("~/Content/Styles/autocomplite-input")
@Scripts.Render("~/bundles/autocomplete_input")
@Scripts.Render("~/bundles/facility-location")

DFI/Views/Facilities/Index.cshtml
@using DFI.Helpers
@using DFI.Data.Emails
@model DFI.Data.Facilities.FacilitySearchDto

@{
    ViewBag.Title = "Practices";
}

<h2>Practices</h2>
<div class="form-group row">
    <label class="col-sm-3" for="Email">Email</label>
    <div class="col-sm-5">
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @data_type = "autocomplete-input", @data_action = "/Facilities/GetFacilityEmails" } })
        @Html.ValidationMessageFor(model => model.Email)
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3" for="FacilityName">Facility Name</label>
    <div class="col-sm-5">
        @Html.EditorFor(model => model.FacilityName, new { htmlAttributes = new { @class = "form-control", @data_type = "autocomplete-input", @data_action = "/Facilities/GetFacilityNames?eFacilityNameFor=FacilitiesList" } })
        @Html.ValidationMessageFor(model => model.FacilityName)
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3" for="PhoneNumber">Phone Number</label>
    <div class="col-sm-5">
        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @data_type = "autocomplete-input", @data_action = "/Facilities/GetFacilityPhoneNumbers" } })
        @Html.ValidationMessageFor(model => model.PhoneNumber)
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3" for="City">City</label>
    <div class="col-sm-5">
        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", @data_type = "autocomplete-input", @data_action = "/Facilities/GetFacilityCities" } })
        @Html.ValidationMessageFor(model => model.City)
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3" for="Status">Status</label>
    <div class="col-sm-5">
        @foreach (var status in Enum.GetNames(typeof(Helper.EState)).Where(x => x != Helper.EState.Deleted.ToString() && x != Helper.EState.New.ToString()))
        {
            <label style="margin-right: 10px;">
                <input type="checkbox" data-group="statuses" value="@((int)Enum.Parse(typeof(Helper.EState), status))" name="Status">
                @status
            </label>
        }
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-4">
        <a href="javascript:void(0)" class="btn btn-primary" id="search">Search</a>
        <a href="javascript:void(0)" class="btn btn-secondary" id="cleanSearch">Clean filters</a>
        <a href="javascript:void(0)" class="btn btn-warning" id="showPopupForSendEmailToAll" data-toggle="modal" data-target="#sendEmailToAllModal">Email to all</a>
        <span style="padding-left: 15px;">
            <i id="spinner" class="fa fa-spinner fa-spin" style="font-size: 27px;/* padding-left: 65px; */"></i>
        </span>
    </div>
</div>
<div id="facilityListPartialView"></div>

@Html.Partial("_SendBulkEmail", new EmailLightDto())
@Html.Partial("_SendDirectlyEmail", new EmailLightDto())
@Html.Partial("_ToastPopups")
@Scripts.Render("~/bundles/facilityTableJS")
@Styles.Render("~/Content/Styles/autocomplite-input")
@Scripts.Render("~/bundles/autocomplete_input")

DFI/Views/Facilities/_FacilitiesList.cshtml
@model DFI.Data.Facilities.ListFacilityDto

@using PagedList.Mvc;

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col" class="d-none d-lg-table-cell">
                <a href="javascript:void(0)" class="notunderline" data-group="column" data-id="email">Email</a>
                <i class="fa fa-sort-alpha-desc" style="display: none" aria-hidden="true"></i>
            </th>
            <th scope="col">
                <a href="javascript:void(0)" class="notunderline" data-group="column" data-id="facilityname">Facility Name</a>
                <i class="fa fa-sort-alpha-desc" style="display: none" aria-hidden="true"></i>
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                <a href="javascript:void(0)" class="notunderline" data-group="column" data-id="phonenumber">Phone Number</a>
                <i class="fa fa-sort-alpha-desc" style="display: none" aria-hidden="true"></i>
            </th>
            <th scope="col" class="d-none d-md-table-cell">
                <a href="javascript:void(0)" class="notunderline" data-group="column" data-id="city">City</a>
                <i class="fa fa-sort-alpha-desc" style="display: none" aria-hidden="true"></i>
            </th>
            <th scope="col">
                <a href="javascript:void(0)" class="notunderline" data-group="column" data-id="facilitystatus">Status</a>
                <i class="fa fa-sort-alpha-desc" style="display: none" aria-hidden="true"></i>
            </th>
            <th scope="col">
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var facility in Model.FacilityShortDtos)
        {
            <tr>
                <td class="d-none d-lg-table-cell text-break">@facility.Email</td>
                <td>@facility.FacilityName</td>
                <td class="d-none d-md-table-cell">@facility.PhoneNumber</td>
                <td class="d-none d-md-table-cell">@facility.City</td>
                <td>@facility.FacilityStatus</td>
                <td>
                    <a href="/facilities/facility/@facility.FacilityId">
                        <i class="fa fa-share-square-o blueIcon" aria-hidden="true"></i>
                    </a>
                    <a href="javascript:void(0)" data-id="sendEmailDirectly" data-email="@facility.Email"
                       title="Send email directly" data-toggle="modal" data-fullname="@facility.FacilityName" data-target="#sendEmailDirectlyModal">
                        <i class="fa fa-envelope envelopIcon" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
Page @(Model.FacilityShortDtos.PageCount < Model.FacilityShortDtos.PageNumber ? 0 : Model.FacilityShortDtos.PageNumber) of @Model.FacilityShortDtos.PageCount

@if (Model.FacilityShortDtos.PageCount > 1)
{
    @Html.PagedListPager(Model.FacilityShortDtos, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), new PagedListRenderOptions()
        {
            MaximumPageNumbersToDisplay = 5
        })
}