DFI/Controllers/RegistratorController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DFI.Data.Accounts;
using DFI.Data.Facilities;
using DFI.Data.GoogleMaps;
using DFI.Data.Temps;
using DFI.Helpers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace DFI.Controllers
{
    public class RegistratorController : Controller
    {
        private readonly ITempService _tempService;
        private readonly IGoogleMapService _googleMapService;
        private readonly IFacilityService _facilityService;
        private readonly ILogger _logger;

        public RegistratorController(ITempService tempService, IGoogleMapService googleMapService, IFacilityService facilityService, ILogger logger)
        {
            _tempService = tempService;
            _googleMapService = googleMapService;
            _facilityService = facilityService;
            _logger = logger;
        }
        private ApplicationUserManager UserManager => HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();

        [HttpGet]
        public ActionResult TempRegistration()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TempRegistration(GetRegistrationFormDto dto)
        {
            if (!CloudflareTurnstile.IsValidRequest(Request, _logger))
            {
                ViewBag.ValidationMessages = "Oops! Something went wrong while submitting the form. Please try again later";
                return View(dto);
            }

            if (ModelState.IsValid)
            {
                var result = _tempService.GetRegistrationForm(dto);

                if (result.FindingResult == EStatusCode.LicenseNotFound)               
                    ModelState.AddModelError("error", "License info not found");
                
                else if (result.FindingResult == EStatusCode.AlreadyExists)
                    ModelState.AddModelError("error", "User already exists");

                else if (result.FindingResult == EStatusCode.AccountWasDeleted)
                    ModelState.AddModelError("error", "User was deleted");

                else if (result.FindingResult == EStatusCode.ValidationGraderError)
                    ModelState.AddModelError("error", result.ValidationGraderError);

                else
                {
                    TempData["TempRegistrationFormDto"] = result;
                    return RedirectToAction("TempRegistrationForm");
                }
            }

            var errors = ModelState.Values.SelectMany(c => c.Errors).Select(x => x.ErrorMessage).ToList();
            if (errors.Any())
                ViewBag.ValidationMessages = string.Join("<br/>", errors);

            return View(dto);
        }

        [HttpGet]
        public ActionResult TempRegistrationForm()
        {
            TempRegistrationFormDto dto = TempData["TempRegistrationFormDto"] as TempRegistrationFormDto;

            if (dto == null)
                return RedirectToAction("TempRegistration");

            return View(dto);
        }

        [HttpPost]
        public ActionResult TempRegistrationForm(TempRegistrationFormDto dto)
        {         
            if (ModelState.IsValid)
            {
                dto.CallbackUrl = Url.Action("ConfirmEmail", "Account",
                    new { userId = "userIdValue", code = "codeConfirmationValue" }, protocol: Request.Url.Scheme);

                _tempService.SubmitRegistrationForm(dto);

                var ip = IpHelper.GetIPAddress(Request);
                _logger.Info($"TempRegistrationForm:: ip = {ip}");

                return new EmptyResult();
            }
            var errors = ModelState.Values.SelectMany(c => c.Errors).Select(x => x.ErrorMessage).ToList();
            return Json(string.Join("<br/>", errors));
        }

        [HttpGet]
        public ActionResult FacilityRegistration()
        {
            var model = new FacilityRegistrationDto();
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateFacilityAccount(FacilityRegistrationDto dto)
        {
            if (!CloudflareTurnstile.IsValidRequest(Request, _logger))
            {
                return Json("Oops! Something went wrong while submitting the form. Please try again later.");
            }

            if (ModelState.IsValid)
            {
                dto.CallbackUrl = Url.Action("ConfirmEmail", "Account",
                    new { userId = "userIdValue", code = "codeConfirmationValue" }, protocol: Request.Url.Scheme);

                var facilityId = _facilityService.SubmitRegistrationForm(dto);

                var ip = IpHelper.GetIPAddress(Request);
                _logger.Info($"CreateFacilityAccount:: ip = {ip}");

                if (!User.IsInRole(Role.Admin))
                    Impersonate(dto.FacilityDto.Email);

                return Json(facilityId);
            }
            var errors = ModelState.Values.SelectMany(c => c.Errors).Select(x => x.ErrorMessage).ToList();
            return Json(string.Join("<br/>", errors));
        }

        private void Impersonate(string email) 
        {
            var userToImpersonate = UserManager.FindByEmailAsync(email).Result;

            var identityToImpersonate = UserManager.CreateIdentityAsync(userToImpersonate,
                    DefaultAuthenticationTypes.ApplicationCookie).Result;

            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            authenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            authenticationManager.SignIn(new AuthenticationProperties()
            {
                IsPersistent = false
            }, identityToImpersonate);
        }
    }
}

DFI/Views/Registrator/FacilityRegistration.cshtml
@using DFI.Helpers
@model DFI.Data.Facilities.FacilityRegistrationDto
@{
    ViewBag.Title = "Please create an account for dental practice";
}

@using (Ajax.BeginForm("CreateFacilityAccount", "Registrator", null, new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    LoadingElementId = "spinner",
    OnSuccess = "fnSuccess"
}, new { enctype = "multipart/form-data", id = "FacilityRegistrationForm" }))
{
    <script type="text/javascript">
        function fnSuccess(data) {
            console.log(data);
            if (data && typeof data !== 'number') {
                $("#validationMessageId").html(data);
                $("#validationMessageId").show();
            } else {
                $("#validationMessageId").hide();
                $("#successMessage").show()
                setTimeout(function () {
                    $("#successMessage").hide();
                    window.location.href = "@(Url.Action("GetFacilityLocation", "Facilities"))" + "?facilityId=" + data;
                }, 2000)
            }
        }
    </script>
    <h2>Please create an account for dental practice</h2>

    <div class="form-group row">
        <div class="col-sm-3">
            <img src='@Url.Action("GetTempPhoto", "Professionals", new {id = Model.FacilityDto.DocumentDtos.FirstOrDefault(c => c.Type == EDocumentType.Photo.ToString())?.Id})' id="facilityPhoto" class="img-fluid img-thumbnail" alt="Photo" />
        </div>
        <div class="col-sm-9">
            <div class="form-group row">
                @Html.LabelFor(c => c.FacilityDto.Photo, "Upload Photo", new { @class = "col-sm-3" })
                <div class="col-sm-4">
                    <div class="custom-file " id="customFile" lang="es">
                        @Html.TextBoxFor(m => m.FacilityDto.Photo, new
                        {
                            type = "file",
                            data_id = "file",
                            id = "facilityPhotoInput",
                            @class = "custom-file-input",
                            aria_describedby = "fileHelp",
                            accept = "image/x-png,image/gif,image/jpeg"
                        })
                        @Html.LabelFor(c => c.FacilityDto.Photo, "Select file...", new { @class = "custom-file-label" })
                        <span class="field-validation-valid" id="custom-file-validation-message">
                            Invalid file selected, valid files are of .jpg, .png, .gif types.
                        </span>
                    </div>
                </div>
                <div class="col-sm-4">
                    <a href="javascript:void(0)" class="btn" id="deletePhoto" title="Delete photo"><i style="color: red;" class="fa fa-trash"></i></a>
                </div>
            </div>

            @foreach (var doc in Model.FacilityDto.DocumentDtos.Where(c => c.Type == EDocumentType.Photo.ToString()))
            {
                <div class="form-group row">
                    <label class="col-sm-3"><i class="fa fa-download" aria-hidden="true"></i></label>
                    <div class="col-sm-4">
                        <a href="/Professionals/DownloadFile/@doc.Id" title="Download" class="notunderline" data-type="@doc.Type" data-id="@doc.Id" data-group="documents">
                            @doc.Name
                        </a>
                    </div>
                    <div class="col-sm-5">
                    </div>
                </div>
            }

            <div class="form-group row">
                @Html.LabelFor(model => model.FacilityDto.FacilityName, "Office Name", new { @class = "col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.FacilityDto.FacilityName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FacilityDto.FacilityName)
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.FacilityDto.Email, "Email", new { @class = "col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.FacilityDto.Email, new { htmlAttributes = new { @class = "form-control", id = "email" } })
                    @Html.ValidationMessageFor(model => model.FacilityDto.Email)
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-3" for="IsBillingEmailSame">Is billing email same</label>
                <div class="col-sm-9">
                    <input type="checkbox" id="IsBillingEmailSame" />
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.FacilityDto.BillingEmail, "Billing email", new { @class = "col-sm-3" })
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.FacilityDto.BillingEmail, new { htmlAttributes = new { @class = "form-control", id = "billingEmail" } })
                    @Html.ValidationMessageFor(model => model.FacilityDto.BillingEmail)
                </div>
            </div>

            <div class="form-group row">
                @Html.LabelFor(model => model.FacilityDto.PayType, "Payment Type", new { @class = "col-sm-3" })

                <div class="col-sm-5">
                    @Html.RadioButtonFor(model => model.FacilityDto.PayType, "1099", new { id = "payType1099" })
                    <label class="form-check-label" for="payType1099">1099 (Independent Contractor)</label>
                </div>

                <div class="col-sm-3">
                    @Html.RadioButtonFor(model => model.FacilityDto.PayType, "W4", new { id = "payTypeW4" })
                    <label class="form-check-label" for="payTypeW4">W4 (Employee)</label>
                </div>
                @Html.ValidationMessageFor(model => model.FacilityDto.PayType)
            </div>
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.Password, "Password", new { @class = "col-sm-3", type = "password" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password)
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(model => model.ConfirmPassword, "Confirm Password", new { @class = "col-sm-3", type = "password" })
        <div class="col-sm-9">
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword)
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            By submitting the form you opt in to receive email and text message notifications, and confirm your agreement with the
            @Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home", routeValues: null, htmlAttributes: new { @target = "_blank" })
        </div>
    </div>

    <div class="alert alert-danger" style="display: none" data-id="validationMessage" id="validationMessageId" role="alert"></div>
    <div class="alert alert-success" style="display: none" id="successMessage" role="alert">Your account has been created. Please verity you email to finish signing up.</div>

    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary" id="createFacilityAccount">Submit and Create location</button>
            @Html.ActionLink("Cancel", "Index", "Home", new { area = "" }, new { @class = "btn btn-secondary" })
            @Html.Partial("_CloudflareWidget")
        </div>
        <div class="col-sm-9">
            <i id="spinner" class="fa fa-spinner fa-spin" style="font-size: 27px; display: none"></i>
        </div>
    </div>
}

<div class="modal fade" id="permanentPlacementAgreementModal" tabindex="-1" role="dialog" aria-labelledby="permanentPlacementAgreementModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="permanentPlacementAgreementLabel">Permanent Placement Agreement</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @{Html.RenderPartial("_PermanentPlacementAgreement");}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" data-dismiss="modal" data-action="accept_permanent_placement_agreement">Accept</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="dentalFillinsFeesModal" tabindex="-1" role="dialog" aria-labelledby="dentalFillinsFeesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="dentalFillinsFeesLabel">Dental Fillins Fees</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @{Html.RenderPartial("_DentalFillinsFeesAgreement");}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" data-dismiss="modal" data-action="accept_dental_fillins_fees_agreement">Accept</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="temporaryStaffingAgreementModal" tabindex="-1" role="dialog" aria-labelledby="temporaryStaffingAgreementModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="temporaryStaffingAgreementLabel">Temporary Staffing Agreement</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @{ Html.RenderPartial("../../Views/Registrator/_TemporaryStaffingAgreementForOffice"); }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" data-dismiss="modal" data-action="accept_temporary_staffing_agreement_for_office">Accept</button>
            </div>
        </div>
    </div>
</div>

<script>
    var selectors = {
        photo: '#facilityPhoto',
        photoInput: '#facilityPhotoInput',
        email: '#email',
        billingEmail: '#billingEmail',
        customFileValidationMessage: '#custom-file-validation-message'
    };
</script>

@Scripts.Render("~/bundles/facilityAccountCreate")

DFI/Views/Registrator/TempRegistration.cshtml
@using DFI.Helpers
@model DFI.Data.Temps.GetRegistrationFormDto
@{
    ViewBag.Title = "TempRegistration";
}

@Html.AntiForgeryToken()

<h2>Please create an account to receive opportunities for temporary placement</h2>

@using (Html.BeginForm("TempRegistration", "Registrator", FormMethod.Post))
{
    <br />
    <P>
        Licensed Professionals please enter your license number and last name to create your account.
        Temporary Dental Assistants will need to provide your radiology license number. If you do not know it, you can look it up here on the website <a href="https://www.pals.pa.gov/#!/page/search" target="_blank">www.pals.pa.gov.</a>
        <br />Enter one of your licenses the rest will be found automatically.
    </P>
    <p>
        Licenses are acceptable only from <b>@Helper.EBoard.StateBoardOfDentistry.GetDisplayName()</b><br />
        Licenses type:
        <ul>
            <li><b>@Helper.ELicenseType.DentalHygienist.GetDisplayName()</b></li>
            <li><b>@Helper.ELicenseType.Dentist.GetDisplayName()</b></li>
            <li><b>@Helper.ELicenseType.ExpandedFunctionDentalAsst.GetDisplayName()</b></li>
        </ul>
    </p>

    <div class="form-group row">
        <label class="col-sm-3" for="LicenseNumber">License Number</label>
        <div class="col-sm-2">
            @Html.EditorFor(model => model.LicenseNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LicenseNumber)
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3" for="LastName">Last Name</label>
        <div class="col-sm-2">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
    </div>

    <p>If you are a dental professional that does not require a license with the state board of dentistry please use links below to create your account.</p>
    <div class="form-group row">
        <label class="col-sm-3" for="IsDentalAssistant">Dental assistant</label>
        <div class="col-sm-9">
            @Html.CheckBoxFor(model => model.IsDentalAssistant, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsDentalAssistant)
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3" for="IsReceptionist">Receptionist</label>
        <div class="col-sm-9">
            @Html.CheckBoxFor(model => model.IsReceptionist, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsReceptionist)
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3" for="IsOfficeManager">Office manager</label>
        <div class="col-sm-9">
            @Html.CheckBoxFor(model => model.IsOfficeManager, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IsOfficeManager)
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-2">
            <button type="submit" class="btn btn-primary" id="btnGetRegistrationForm">Submit</button><i id="spinner" class="fa fa-spinner fa-spin float-right" style="font-size: 27px; display: none"></i>
            @Html.Partial("_CloudflareWidget")
        </div>    
    </div>

    <div class="alert alert-danger" style="display: none" id="validationMessageGetForm" role="alert">@ViewBag.ValidationMessages</div>
}


@Scripts.Render("~/bundles/tempRegistration")

DFI/Views/Registrator/_DentalFillinsFeesAgreement.cshtml
<h5>DFI Placement Fee</h5>
<p>
    <span><b>$58.30</b> temporary placement/day</span><br />
    <span><b>$125.00</b> dentist temporary placement/day</span><br />
    <span><b>+15%</b> placement fee < 24 hr notice</span>
</p>
<p>
    If client cancels after temporary staff is procured the placement fee will be charged.
    If client cancels temporary staff  < 12hrs, client is responsible to pay temporary staff 50% of expected hourly wages.
</p>
<h5>Temporary Staff Hourly Rates</h5>
<p>
    Hourly rates of temporary staff vary depending upon position, experience, notice given for assignment and travel distance.  All rates will be quoted upon assignment confirmation.
    Client is responsible for direct payment to temporary employee per staffing agreement.
</p>
<h5>Permanent Placement Rates</h5>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Dental Hygienist</label>
    <div class="col-sm-9">
        <span>$1050.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Practice Manager</label>
    <div class="col-sm-9">
        <span>$950.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">EFDA</label>
    <div class="col-sm-9">
        <span>$900.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Dental Assistant</label>
    <div class="col-sm-9">
        <span>$850.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Administrative</label>
    <div class="col-sm-9">
        <span>$750.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Dentist</label>
    <div class="col-sm-9">
        <span>$2,250.00 / day scheduled per week</span>
    </div>
</div>
<p>Permanent Placement Agreement and payment to DFI shall be completed before hire.</p>
<p>All rates subject to PA sales tax payable in full by client.</p>

DFI/Views/Registrator/_PermanentPlacementAgreement.cshtml
<p>
    Throughout this Agreement, the parties shall be referred to as follows: Dental office or Doctor shall be referred to as ‘Client’. Dental Fillins, LLC. shall be referred to as ‘DFI’.
    Please read and fully understand the following before signing:
</p>
<p>
    Client, has advised DFI that it may be interested in employing, engaging or retaining, the temporary staff provided by DFI pursuant to the Staffing Agreement.
    As such, Client hereby acknowledges and agrees that all permanent placement assignments (whether as employees or independent contractors) for
    temporary staff who have been provided by DFI shall be arranged through DFI. No oral or written contracts or any other arrangements shall be arranged directly by the Client through temporary staff.
    Arranging a permanent position directly with temporary staff will be considered a breach of contract and Client will be subject to all legal and equitable remedies that may be pursued by DFI.
</p>
<p>
    Client is required to pay a permanent placement fee to DFI if employee was first provided to Client’s office by DFI. If employee was provided to Client’s office through other means or agencies after first DFI assignment,
    Client is still responsible to pay a permanent placement fee to DFI.
</p>
<p>Permanent placement fees paid to DFI are as follows:</p>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Dental Hygienist</label>
    <div class="col-sm-9">
        <span>$1050.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Practice Manager</label>
    <div class="col-sm-9">
        <span>$950.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">EFDA</label>
    <div class="col-sm-9">
        <span>$900.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Dental Assistant</label>
    <div class="col-sm-9">
        <span>$850.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Administrative</label>
    <div class="col-sm-9">
        <span>$750.00 / day scheduled per week</span>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-3 font-weight-bold">Dentist</label>
    <div class="col-sm-9">
        <span>$2,250.00 / day scheduled per week</span>
    </div>
</div>
<p>Permanent Placement Agreement and payment to DFI shall be completed before hire.</p>
<p>Permanent placement fees are paid in full on the temporary hire date or the daily temp rate will accrue.</p>
<p>
    Client, will receive a prorated credit for a future permanent placement if a permanently placed staff’s employment is terminated for any reason within ninety
    (90) days of his or her start date; no refunds will be made to Client of any such amounts.
</p>
<p>
    All placement fees are subject to sales tax, which is payable in full by the Client.
</p>
<p>
    Client assumes all legal responsibility for permanently placed staff upon signing this Addendum.
    Client shall hold DFI harmless from any and all liability, loss, claims or damages associated with any alleged negligence or malpractice committed by permanently placed staff.
</p>
<p>Each of DFI and Client agree to be bound by the terms of this Agreement.</p>
<p>IN WITNESS WHEREOF, the parties hereto have executed this Addendum</p>

DFI/Views/Registrator/_TemporaryStaffingAgreement.cshtml
<p>Throughout this Agreement, the parties shall be referred to as the following: 
    Dental Fillins, LLC. shall be referred to as ‘DFI’. Temporary staff shall be referred to as ‘I’. Doctors/ dental practices shall be referred to as ‘Client’. 
    Please read and fully understand the following before agreeing.</p>
<p>Please read and fully understand the following before signing:</p>
<ol>
    <li>I agree not to become an employee or independent contractor of any Client or to contract (orally, in writing, or digitally) directly or indirectly with any Client for a period of twelve (12) months from my last DFI temporary assignment.   Contracting or accepting a permanent or temporary position from Client without complying with this Agreement would be considered breach of contract and I would be subject to appropriate legal action (including entitlements to legal and equitable relief) from DFI.</li>

    <li>If I am offered a permanent or temporary position during the term of this Agreement or for twelve (12) months thereafter, I agree to contact DFI before making any arrangements.  I recognize that all Clients are required to process all requests for permanent and temporary placement through DFI and to pay a fee to DFI for such placements.</li>

    <li>I represent that, if required by law, I possess all licenses, certifications, or other registrations necessary to provide services to Clients.</li>

    <li>I agree to accept payments directly from Client as arranged through DFI and Client.  I acknowledge and agree that I am not an employee of DFI and that Client, and not DFI, is solely responsible to compensate me for services rendered to a Client.</li>

    <li>I agree to follow OSHA and HIPAA standards of infection control and privacy if compliance per federal, state, and local laws and regulations, as well as the rules and guidelines of the Client while on DFI assignment.</li>

    <li>I agree to perform my tasks to the best of my abilities and exercise proper judgment in reference to DFI assignment.  I agree to use my best professional standards of quality care.  I agree to immediately report any problems experienced with Clients to DFI.  DFI will take appropriate action to attempt to address any unfavorable situations.</li>

    <li>Once assigned, I agree to contact DFI immediately with any change to my availability.  I must provide DFI with at least forty-eight (48) hours notice for canceling a DFI temporary assignment.</li>

    <li>We may terminate or suspend your account, without notice or liability, for any reason, including without limitation if you breach this agreement.  If you wish to terminate your account, you may discontinue using the service.</li>

    <li>I agree to hold DFI harmless and release it from any and all liability for any harm, loss, liability, claim, or damage that may come to me as a result of a DFI assignment, including but not limited to any injuries or liabilities that arise in connection with travel to and from a DFI assignment.</li>

    <li>Each of DFI and I are to be bound by the terms of this agreement.</li>
</ol>
<p>IN WITNESS WHEREOF, the parties hereto have executed this Agreement</p>