DFI/Controllers/ProfessionalReviewsController.cs
using System;
using System.Web.Mvc;
using DFI.Data.Accounts;
using DFI.Data.ProfessionalReviews;

namespace DFI.Controllers
{
    public class ProfessionalReviewsController : Controller
    {
        private readonly IProfessionalReviewService _professionalReviewService;

        public ProfessionalReviewsController(IProfessionalReviewService professionalReviewService)
        {
            _professionalReviewService = professionalReviewService;
        }
        
        [HttpGet]
        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        // before change the URL of this action, pay attention to EmailConstants.ProfessionalReviewLinkTemplate constant
        public ActionResult Review(int tempId, int requestId)
        {
            var userEmail = User.Identity.Name;
            var hasAccessToReview = _professionalReviewService.HasAccessToCreateReview(tempId, requestId, userEmail);

            if (hasAccessToReview.Success == false)
                return RedirectToAction("ReviewDenay", new { message = string.Join(", ", hasAccessToReview.Messages) });

            return View();
        }

        [HttpPost]
        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        public ActionResult Review(ProfessionalReviewDto dto)
        {
            if (ModelState.IsValid)
            {
                var userEmail = User.Identity.Name;
            
                var result = _professionalReviewService.AddReview(dto, userEmail);

                if (result.Success)
                    return RedirectToAction("ReviewWasSentSuccessfully");
                else
                    return RedirectToAction("ReviewDenay", new { message = string.Join(", ", result.Messages) });
            }
            else
            {
                return View(dto);
            }
        }

        [HttpGet]
        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        public ActionResult ReviewDenay(string message)
        {
            return View("ReviewDenay", model: message);
        }
        
        [HttpGet]
        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        public ActionResult ReviewWasSentSuccessfully()
        {
            return View("ReviewWasSentSuccessfully");
        }

        [HttpGet]
        [Authorize(Roles = Role.Admin + "," + Role.Facility)]
        public PartialViewResult GetReviewDetailToLeaveReview(int tempId, int requestId)
        {
            var model = _professionalReviewService.CreateInitialModel(tempId, requestId);      
            return PartialView("_ReviewDetail", model);
        }


        [HttpGet]
        [Authorize(Roles = Role.Admin + "," + Role.Facility + "," + Role.Temp)]
        public PartialViewResult GetReadonlyReviewDetail(int tempId, int requestId)
        {
            var model = _professionalReviewService.GetReadonlyReview(tempId, requestId);
            if (model == null)
                return PartialView("_NotYetReview");

            return PartialView("_ReviewDetail", model);
        }

        [HttpGet]
        [Authorize(Roles = Role.Admin)]
        public PartialViewResult GetAllProfessionalReviews(int? tempId, int pageNumber)
        {
            if(tempId == null)
            {
                throw new ArgumentException("Temp is null");
            }
            var reviews = _professionalReviewService.GetListOfReviews(tempId.Value, pageNumber);
            return PartialView("_AllReviewsList", reviews);
        }

        [HttpGet]
        [Authorize(Roles = Role.Admin)]
        public ActionResult AllProfessionalReviews(int? tempId, string firstName, string lastName)
        {
            if (tempId == null)
            {
                throw new ArgumentException("Temp is null");
            }

            ViewBag.FirstName = firstName;
            ViewBag.LastName = lastName;

            return View();
        }
    }
}

DFI/Views/ProfessionalReviews/AllProfessionalReviews.cshtml
@{
    ViewBag.Title = "AllProfessionalReviews";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    var firstName = char.ToUpper(ViewBag.FirstName[0]) + ViewBag.FirstName.Substring(1).ToLower();
    var lastName = char.ToUpper(ViewBag.LastName[0]) + ViewBag.LastName.Substring(1).ToLower();
}

<h2>All Professional's Reviews for @firstName @lastName</h2>

<div id="allReviewsDiv"></div>

@Scripts.Render("~/bundles/all-reviews-table")

DFI/Views/ProfessionalReviews/Review.cshtml
@{
    ViewBag.Title = "Professional Review";
}
@section scripts {
    @Scripts.Render("~/bundles/jquery-bar-rating")
    @Scripts.Render("~/bundles/professional-review")
    @Scripts.Render("~/bundles/reviewDetail")
}

@section styles {
    @Styles.Render("~/Content/css/jquery-bar-rating")
}

<h2>Professional Review</h2>
<div id="review-detail"></div>

DFI/Views/ProfessionalReviews/ReviewDenay.cshtml
@{
    ViewBag.Title = "Review denay";
}

<div class="alert alert-danger" role="alert">
    @Model
</div>

DFI/Views/ProfessionalReviews/ReviewWasSentSuccessfully.cshtml
@{
    ViewBag.Title = "Review was sent successfully";
}

<div class="alert alert-success" role="alert">
    Review was sent successfully
</div>

DFI/Views/ProfessionalReviews/_AllReviewsList.cshtml
@model DFI.Data.ProfessionalReviews.PageProfessionalReviews
@using PagedList.Mvc;

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col" class="d-none d-lg-table-cell">RequestId</th>
            <th scope="col" class="d-none d-lg-table-cell">Position</th>
            <th scope="col" class="d-none d-lg-table-cell">Rating</th>
            <th scope="col" class="d-none d-lg-table-cell">IsBlocked</th>
            <th scope="col" class="d-none d-lg-table-cell">Description</th>
            <th scope="col" class="d-none d-lg-table-cell">Questionnaire</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var temp in Model.OwnProfessionalReviews)
        {
        <tr>
            <td class="d-none d-md-table-cell">@temp.RequestId</td>
            <td class="d-none d-md-table-cell">@temp.Position</td>
            <td class="d-none d-md-table-cell">@temp.Rating</td>
            <td class="d-none d-lg-table-cell">@temp.IsBlocked</td>
            <td class="d-none d-md-table-cell">@temp.Description</td>
            <td class="d-none d-md-table-cell">
                <p>Did Arrive In Timely Manner: @temp.DidArriveInTimelyManner</p>
                <p>Did Present In Professional Attire: @temp.DidPresentInProfessionalAttire</p>
                <p>Did Interact Well With Staff: @temp.DidInteractWellWithStaff</p>
                <p>Did Interact Well With Customers: @temp.DidInteractWellWithCustomers</p>
                <p>Was Competent In Digital Charting And Documentation: @temp.WasCompetentInDigitalChartingAndDocumentation</p>
            </td>
        </tr>
        }
    </tbody>
</table>
<br />
Page @(Model.OwnProfessionalReviews.PageCount < Model.OwnProfessionalReviews.PageNumber ? 0 : Model.OwnProfessionalReviews.PageNumber) of @Model.OwnProfessionalReviews.PageCount

@if (Model.OwnProfessionalReviews.PageCount > 1)
{
    @Html.PagedListPager(Model.OwnProfessionalReviews, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), new PagedListRenderOptions()
        {
            MaximumPageNumbersToDisplay = 5
        })
}

DFI/Views/ProfessionalReviews/_NotYetReview.cshtml
<p>Review has not been added</p>

DFI/Views/ProfessionalReviews/_ReviewDetail.cshtml
@model DFI.Data.ProfessionalReviews.ProfessionalReviewDto


@using (Html.BeginForm("Review", "ProfessionalReviews"))
{
    @Html.HiddenFor(x => x.TempId)
    @Html.HiddenFor(x => x.RequestId)
    @Html.HiddenFor(x => x.RequestDisplayName)
    @Html.HiddenFor(x => x.TempDisplayName)
    @Html.HiddenFor(x => x.TempPhoto)
    @Html.HiddenFor(x => x.IsReadonly)

    <div class="form-group row">
        <label class="col-sm-3">Request date(s)</label>
        <div class="col-sm-9">
            @Html.ActionLink(Model.RequestDisplayName, "Edit", "Requests", new { id = Model.RequestId }, null)
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3">Position</label>
        <div class="col-sm-9">
            @Html.DisplayFor(m => m.Position)
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-3">Professional</label>
        <div class="col-sm-9">
            <span>@Model.TempDisplayName</span>
            @if (Model.TempPhoto.Length > 0)
            {
                <img class="img-fluid" src="@Model.TempPhoto" alt="@Model.TempDisplayName" style="display: flex; width: 300px;" />
            }
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.Rating, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @if (Model.IsReadonly)
            {
                <span><b style="font-size: xx-large;">@Model.Rating</b></span>
            }
            else
            {
                @Html.DropDownListFor(
                    m => m.Rating,
                    Enumerable.Range(1, 10).Select(i => new SelectListItem {Text = i.ToString(), Value = i.ToString()}))
                @Html.ValidationMessageFor(x => x.Rating)
            }

        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.DidArriveInTimelyManner, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.RadioButtonFor(x => x.DidArriveInTimelyManner, true, new {@data_group = "disabled"}) <label class="mr-5" data-group="label-radio">Yes</label>
            @Html.RadioButtonFor(x => x.DidArriveInTimelyManner, false, new {@data_group = "disabled"}) <label data-group="label-radio">No</label>
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.DidPresentInProfessionalAttire, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.RadioButtonFor(x => x.DidPresentInProfessionalAttire, true, new { @data_group = "disabled" }) <label class="mr-5" data-group="label-radio">Yes</label>
            @Html.RadioButtonFor(x => x.DidPresentInProfessionalAttire, false, new { @data_group = "disabled" }) <label data-group="label-radio">No</label>
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.DidInteractWellWithStaff, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.RadioButtonFor(x => x.DidInteractWellWithStaff, true, new { @data_group = "disabled" }) <label class="mr-5" data-group="label-radio">Yes</label>
            @Html.RadioButtonFor(x => x.DidInteractWellWithStaff, false, new { @data_group = "disabled" }) <label data-group="label-radio">No</label>
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.DidInteractWellWithCustomers, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.RadioButtonFor(x => x.DidInteractWellWithCustomers, true, new { @data_group = "disabled" }) <label class="mr-5" data-group="label-radio">Yes</label>
            @Html.RadioButtonFor(x => x.DidInteractWellWithCustomers, false, new { @data_group = "disabled" }) <label data-group="label-radio">No</label>
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.WasCompetentInDigitalChartingAndDocumentation, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.RadioButtonFor(x => x.WasCompetentInDigitalChartingAndDocumentation, true, new { @data_group = "disabled" }) <label class="mr-5" data-group="label-radio">Yes</label>
            @Html.RadioButtonFor(x => x.WasCompetentInDigitalChartingAndDocumentation, false, new { @data_group = "disabled" }) <label data-group="label-radio">No</label>
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.IsBlocked, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.EditorFor(x => x.IsBlocked, new { htmlAttributes = new { @data_group = "disabled" } })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(x => x.Description, new { @class = "col-sm-3" })
        <div class="col-sm-9">
            @Html.EditorFor(x => x.Description, new { htmlAttributes = new { @class = "form-control", @data_group="disabled" } })
            @Html.ValidationMessageFor(x => x.Description)
        </div>
    </div>

    if (Model.IsReadonly == false)
    {
        <div class="form-group row">
            <div class="col-sm-12 my-2">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    }
}